apiVersion: v1
kind: Service
metadata:
  name: auth0-svc
spec:
  type: ClusterIP
  selector:
    app: auth0
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth0-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth0
  template:
    metadata:
      labels:
        app: auth0
    spec:
      containers:
      - name: auth0
        image: 211125418324.dkr.ecr.ap-northeast-2.amazonaws.com/auth0
        ports:
        - containerPort: 3000
        env:
        - name: STREAMLIT_APP_URL
          value: "http://54.180.129.95:32314/app"
